apiVersion: apps/v1
kind: Deployment
metadata:
  name: apis
spec:
  selector:
    matchLabels:
      app: apis
  replicas: 4
  template:
    metadata:
      labels:
        app: apis
    spec:
      containers:
      - name: main-api
        image: penguin1234/md-apis:0.1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: myregistrykey