apiVersion: apps/v1
kind: Deployment
metadata:
  name: util-avgget
spec:
  selector:
    matchLabels:
      app: util-avgget
  replicas: 2
  template:
    metadata:
      labels:
        app: util-avgget
    spec:
      containers:
      - name: getaverage
        image: penguin1234/mind-detector-utils-getavg:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: myregistrykey