apiVersion: apps/v1
kind: Deployment
metadata:
  name: util-avgset
spec:
  selector:
    matchLabels:
      app: util-avgset
  replicas: 3
  template:
    metadata:
      labels:
        app: util-avgset
    spec:
      containers:
      - name: setaverage
        image: penguin1234/mind-detector-utils-postavg:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: myregistrykey