apiVersion: apps/v1
kind: Deployment
metadata:
  name: util-center
spec:
  selector:
    matchLabels:
      app: util-center
  replicas: 2
  template:
    metadata:
      labels:
        app: util-center
    spec:
      containers:
      - name: getcenters
        image: penguin1234/mind-detector-utils-getcenters:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: myregistrykey