apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
spec:
  selector:
    matchLabels:
      app: model
  replicas: 4
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - image: penguin1234/md-model-api:1.0.4
        imagePullPolicy: Always
        name: model-api
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 3
      imagePullSecrets:
      - name: myregistrykey