apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
spec:
  selector:
    matchLabels:
      app: model
  replicas: 4
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - image: penguin1234/md-model-api:1.0.2
        imagePullPolicy: Always
        name: model-api
        ports:
        - containerPort: 5000
      - image: penguin1234/md-model:1.0.0
        imagePullPolicy: Always
        name: model-engine
        ports:
        - containerPort: 7000
      imagePullSecrets:
      - name: myregistrykey